### PR TITLE
docs: man page script

### PR DESCRIPTION
**Pull request by AgusDOLARD**
This PR [#27] add the capability to automatically generate manpages based on the cli.App

### CODE REVIEW

**Review by joshmedeski — CHANGES_REQUESTED** [review]
Can you add instructions for how to generate the man file and how we would set this it to update in CI?

**Comment by AgusDOLARD** [comment]
you have to run 

''' go
go run docs/generate.go
'''

**Comment by AgusDOLARD** [comment]
fixed

**Comment by joshmedeski** [comment]
Thanks! I'll figure out how homebrew will install the man page on install.

**Pull request merged**
